import type { Metadata } from "next";
import  Head  from "next/head";
import {Kanit} from 'next/font/google'
import "./globals.css";

const kanit = Kanit({subsets:['latin'],weight:['400','700']})

export const metadata: Metadata = {
  title: "Amit.dev",
  description: "Generated by create next app",
  icons:{
    icon: "/name.jpeg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
    <Head><link rel="icon" href="/name.jpeg" /></Head>
      <body
        className={kanit.className + 'bg-white dark:bg-black text-black dark:text-white'}
      >
        {children}
      </body>
    </html>
    </>
  );
}
