import type { Metadata } from "next";
import  Head  from "next/head";
import {Ubuntu} from "next/font/google";
import {Lexend} from 'next/font/google';
import "./globals.css";

const ubuntu = Ubuntu({subsets:['latin'],weight:['300','400','500','700']})
const geo = Lexend({subsets:['latin'],weight:['200','300','500','600','700','800','900']})

export const metadata: Metadata = {
  title: "Amit.dev",
  description: "Generated by create next app",
  icons:{
    icon: "/name.jpeg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
    <Head><link rel="icon" href="/name.jpeg" /></Head>
      <body
        className={geo.className + 'bg-white dark:bg-black text-black dark:text-white'}
      >
        {children}
      </body>
    </html>
    </>
  );
}
